"""
effectiveness_sets.py — compute "Only-by" precisely as set differences (RQ2/RQ3)

In Section 4.3 of the paper, "Only by Snapshot" / "Only by Non-Snapshot" are defined not as a
plain subtraction of coverage percentages, but as **differences of covered-line sets / detected-
mutant sets**.

  - Only by Snapshot     = All - Non-Snapshot
                           (= the region covered/detected only by snapshot tests)
  - Only by Non-Snapshot = All - Snapshot

For each project we run the tests three ways (All / Snapshot only / Non-Snapshot only), build sets
from the resulting reports, take differences, and express them as a percentage (%) of the total.

Input reports:
  - Coverage:  Jest (Istanbul) coverage-final.json
               generated by jest --coverage --coverageReporters=json
  - Mutation:  Stryker mutation.json (--reporters json)
"""

from __future__ import annotations

import json
from pathlib import Path

CATEGORIES = ["All", "Snapshot", "Non-Snapshot",
              "Only by Snapshot", "Only by Non-Snapshot"]


# ===========================================================================
# Coverage (Istanbul coverage-final.json)
# ===========================================================================
def coverage_statement_universe_and_set(path: str | Path) -> tuple[set, set]:
    """Return (all-statements set, covered set) from a coverage-final.json.

    Each statement is uniquely identified by (file path, statementId).
    """
    data = json.loads(Path(path).read_text())
    universe: set = set()
    covered: set = set()
    for file_path, fc in data.items():
        s_counts = fc.get("s", {})  # statementId -> hit count
        for sid, hits in s_counts.items():
            key = (file_path, sid)
            universe.add(key)
            if hits and hits > 0:
                covered.add(key)
    return universe, covered


def coverage_only_by(all_path: str | Path,
                     snapshot_path: str | Path,
                     non_snapshot_path: str | Path) -> dict[str, float]:
    """Compute the 5-category statement coverage (%) from three coverage-final.json files.

    Denominator = number of all statements from the All run (= the measured population).
    """
    universe, cov_all = coverage_statement_universe_and_set(all_path)
    _, cov_snap = coverage_statement_universe_and_set(snapshot_path)
    _, cov_nonsnap = coverage_statement_universe_and_set(non_snapshot_path)
    total = len(universe) or 1

    only_snap = cov_all - cov_nonsnap
    only_nonsnap = cov_all - cov_snap
    pct = lambda s: 100.0 * len(s) / total
    return {
        "All": pct(cov_all),
        "Snapshot": pct(cov_snap & universe),
        "Non-Snapshot": pct(cov_nonsnap & universe),
        "Only by Snapshot": pct(only_snap),
        "Only by Non-Snapshot": pct(only_nonsnap),
    }


def coverage_full_sets(all_path: str | Path,
                       snapshot_path: str | Path,
                       non_snapshot_path: str | Path) -> dict[str, float]:
    """Compute the 6 categories of paper Fig.6 with **true set operations** (fixes ST∩NonST).

    coverage_only_by does not derive ST∩NonST; the figure code used to subtract
    `cov_snap + cov_nonsnap - cov_all`, which produced negative values (-100) for
    repositories where cov_all exceeds cov_snap ∪ cov_nonsnap. This function takes
    ∪ / ∩ / differences directly from cov_snap / cov_nonsnap, so results are always 0..100.

    Denominator = number of all statements from the All run (universe).
    - "All"           : coverage of the combined run of all three kinds (~ paper's ST∪NonST)
    - "Union"         : |cov_snap ∪ cov_nonsnap| (true union of the separate runs; reference)
    - "Common"        : |cov_snap ∩ cov_nonsnap|            (ST∩NonST)
    - "Only by *"      : pure set difference cov_snap - cov_nonsnap (paper-text definition)
    - "Only by * (marginal)": legacy definition cov_all - cov_other  (marginal contribution; for comparison)
    """
    universe, cov_all = coverage_statement_universe_and_set(all_path)
    _, cov_snap = coverage_statement_universe_and_set(snapshot_path)
    _, cov_nonsnap = coverage_statement_universe_and_set(non_snapshot_path)
    cov_snap &= universe
    cov_nonsnap &= universe
    total = len(universe) or 1
    pct = lambda s: 100.0 * len(s) / total
    return {
        "All": pct(cov_all),
        "Snapshot": pct(cov_snap),
        "Non-Snapshot": pct(cov_nonsnap),
        "Union": pct(cov_snap | cov_nonsnap),
        "Common": pct(cov_snap & cov_nonsnap),
        "Only by Snapshot": pct(cov_snap - cov_nonsnap),
        "Only by Non-Snapshot": pct(cov_nonsnap - cov_snap),
        "Only by Snapshot (marginal)": pct(cov_all - cov_nonsnap),
        "Only by Non-Snapshot (marginal)": pct(cov_all - cov_snap),
    }


# ===========================================================================
# Mutation (Stryker mutation.json)
# ===========================================================================
DETECTED_STATUSES = {"Killed", "Timeout"}


def _mutant_key(file_path: str, m: dict) -> tuple:
    """A key that identifies a mutant stably across runs.

    Stryker's mutant id can change between runs, so we identify a mutant by
    (file, mutator name, location, replacement).
    """
    loc = m.get("location", {})
    start = loc.get("start", {})
    end = loc.get("end", {})
    return (
        file_path,
        m.get("mutatorName"),
        start.get("line"), start.get("column"),
        end.get("line"), end.get("column"),
        m.get("replacement"),
    )


def mutation_universe_and_killed(path: str | Path) -> tuple[set, set]:
    """Return (all-mutants set, detected set) from a Stryker mutation.json."""
    data = json.loads(Path(path).read_text())
    universe: set = set()
    killed: set = set()
    for file_path, fc in data.get("files", {}).items():
        for m in fc.get("mutants", []):
            key = _mutant_key(file_path, m)
            universe.add(key)
            if m.get("status") in DETECTED_STATUSES:
                killed.add(key)
    return universe, killed


def mutation_only_by(all_path: str | Path,
                     snapshot_path: str | Path,
                     non_snapshot_path: str | Path) -> dict[str, float]:
    """Compute the 5-category mutation score (%) from three mutation.json files.

    Denominator = number of all mutants (the population from the All run).
    """
    universe, killed_all = mutation_universe_and_killed(all_path)
    _, killed_snap = mutation_universe_and_killed(snapshot_path)
    _, killed_nonsnap = mutation_universe_and_killed(non_snapshot_path)
    total = len(universe) or 1

    only_snap = killed_all - killed_nonsnap
    only_nonsnap = killed_all - killed_snap
    pct = lambda s: 100.0 * len(s) / total
    return {
        "All": pct(killed_all),
        "Snapshot": pct(killed_snap & universe),
        "Non-Snapshot": pct(killed_nonsnap & universe),
        "Only by Snapshot": pct(only_snap),
        "Only by Non-Snapshot": pct(only_nonsnap),
    }


def covered_mutation_only_by(all_path: str | Path,
                             snapshot_path: str | Path,
                             non_snapshot_path: str | Path) -> dict[str, float]:
    """Mutation score over covered code (the paper's Covered Mutation Score).

    Excludes NoCoverage from the denominator: (Killed+Timeout)/(Killed+Timeout+Survived).
    """
    def universe_killed_covered(path):
        data = json.loads(Path(path).read_text())
        uni, killed = set(), set()
        for fp, fc in data.get("files", {}).items():
            for m in fc.get("mutants", []):
                if m.get("status") == "NoCoverage":
                    continue
                key = _mutant_key(fp, m)
                uni.add(key)
                if m.get("status") in DETECTED_STATUSES:
                    killed.add(key)
        return uni, killed

    # The covered score uses, as denominator, the mutants that each test set "covers by itself"
    # (paper Fig.7b definition). The old implementation divided ST/Non-ST by the All covered set,
    # which made the ST covered score unfairly low (the main cause of 79.2 -> 29.8). Here each
    # category is divided by its own covered population.
    uni_all, killed_all = universe_killed_covered(all_path)
    uni_snap, killed_snap = universe_killed_covered(snapshot_path)
    uni_non, killed_nonsnap = universe_killed_covered(non_snapshot_path)
    pct = lambda s, uni: 100.0 * len(s) / (len(uni) or 1)
    return {
        "All": pct(killed_all, uni_all),
        "Snapshot": pct(killed_snap, uni_snap),
        "Non-Snapshot": pct(killed_nonsnap, uni_non),
        # Only-by is the "marginal contribution relative to the All covered population". Fig.7b only
        # draws the 3 categories All/ST/NonST, so these are reference values (denominator = All covered set).
        "Only by Snapshot": pct(killed_all - killed_nonsnap, uni_all),
        "Only by Non-Snapshot": pct(killed_all - killed_snap, uni_all),
    }


def mutation_by_mutator(all_path: str | Path,
                        snapshot_path: str | Path,
                        non_snapshot_path: str | Path) -> dict[str, dict]:
    """Compute per-mutatorName kill rate (%) split by ST / Non-ST / All (paper Table 4).

    kill rate(mutator) = |detected mutants of that mutator| / |total of that mutator (All-run population)|.
    The denominator uses All, which is common to all three modes (the mutant population is invariant
    because the code is identical).
    Returns: {mutatorName: {"total": int, "ST": pct, "Non-ST": pct, "All": pct}}
    """
    from collections import defaultdict

    def per_mutator(path):
        data = json.loads(Path(path).read_text())
        uni = defaultdict(set)
        killed = defaultdict(set)
        for fp, fc in data.get("files", {}).items():
            for m in fc.get("mutants", []):
                mut = m.get("mutatorName")
                key = _mutant_key(fp, m)
                uni[mut].add(key)
                if m.get("status") in DETECTED_STATUSES:
                    killed[mut].add(key)
        return uni, killed

    uni_all, killed_all = per_mutator(all_path)
    _, killed_snap = per_mutator(snapshot_path)
    _, killed_nonsnap = per_mutator(non_snapshot_path)

    out: dict[str, dict] = {}
    for mut, uni in uni_all.items():
        total = len(uni) or 1
        out[mut] = {
            "total": len(uni),
            "ST": 100.0 * len(killed_snap.get(mut, set()) & uni) / total,
            "Non-ST": 100.0 * len(killed_nonsnap.get(mut, set()) & uni) / total,
            "All": 100.0 * len(killed_all.get(mut, set()) & uni) / total,
        }
    return out


def aggregate_mutator_table(per_project: list[dict[str, dict]]) -> dict[str, dict]:
    """Aggregate per-repository mutation_by_mutator into a per-mutator median kill rate.

    Paper Table 4 reports a "median kill rate across repositories" for ST/Non-ST, so for each
    mutator we take the median of the ST/Non-ST values across repositories.
    Returns: {mutatorName: {"ST": median, "Non-ST": median, "Diff": ST-NonST, "n": repos}}
    """
    import statistics
    from collections import defaultdict
    st = defaultdict(list)
    nost = defaultdict(list)
    for proj in per_project:
        for mut, v in proj.items():
            if v.get("ST") is not None:
                st[mut].append(float(v["ST"]))
            if v.get("Non-ST") is not None:
                nost[mut].append(float(v["Non-ST"]))
    out = {}
    for mut in sorted(set(st) | set(nost)):
        s = statistics.median(st[mut]) if st[mut] else 0.0
        n = statistics.median(nost[mut]) if nost[mut] else 0.0
        out[mut] = {"ST": s, "Non-ST": n, "Diff": s - n,
                    "n": max(len(st[mut]), len(nost[mut]))}
    return out


# ===========================================================================
# Aggregation over multiple projects (into distribution data)
# ===========================================================================
def aggregate_projects(per_project: list[dict[str, float]]) -> dict[str, list[float]]:
    """Aggregate each project's 5-category values into per-category distributions."""
    out: dict[str, list[float]] = {c: [] for c in CATEGORIES}
    for proj in per_project:
        for c in CATEGORIES:
            if c in proj and proj[c] is not None:
                out[c].append(float(proj[c]))
    return out


if __name__ == "__main__":
    # Self-test with synthetic JSON (to sanity-check the schema)
    import tempfile

    cov = {
        "/src/a.js": {"s": {"0": 1, "1": 0, "2": 3}},
        "/src/b.js": {"s": {"0": 1, "1": 1}},
    }
    cov_snap = {"/src/a.js": {"s": {"0": 1, "1": 0, "2": 0}}, "/src/b.js": {"s": {"0": 0, "1": 0}}}
    cov_non = {"/src/a.js": {"s": {"0": 1, "1": 0, "2": 3}}, "/src/b.js": {"s": {"0": 0, "1": 1}}}
    d = tempfile.mkdtemp()
    for nm, obj in [("all", cov), ("snap", cov_snap), ("non", cov_non)]:
        Path(d, f"{nm}.json").write_text(json.dumps(obj))
    print("coverage only-by:", coverage_only_by(
        Path(d, "all.json"), Path(d, "snap.json"), Path(d, "non.json")))
